//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_list
    {
        public int food_id { get; set; }
        public int c_id { get; set; }
        public string food_name { get; set; }
        public int price { get; set; }
    
        public virtual categories categories { get; set; }
    }
}
