//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders2
    {
        public int o_id { get; set; }
        public int table_id { get; set; }
        public int food_id { get; set; }
        public int piece { get; set; }
    }
}
